### ISSUE TITLE
Re-use vendor specific USB

### ISSUE THREAD

**Issue by maaamcube** [FCare/USBTo3DO#1]
Hello everyone,
Can the vendor specific (vendor_host.c) of this repo work with other vendor specific USB ? if not, what i have to look in for to make it work with any vendor ?
Thanks.

**Comment by FCare** [comment]
As vendor specific means, it is vendor specific... So you can not just get one generic file to cover all the possible vendors. Each vendor is using its own defined mechanism to extend USB standard to its needs.
This vendor specific mainly covers XBOX360 compatible devices. If you need more vendor, you have to find the information of this vendor and extend the vendor specific accordingly.

**Comment by maaamcube** [comment]
@FCare thanks for your reply.
This is the vendor that was given me to work with : https://github.com/maaamcube/USB-device-Vendor-specific
There is no documentation about, can you check it and tell me what i have to look to build my own vendor host ?
